const ingredients = [
  {
    name: "Chicken Breast",
    protein: 31,
    carbs: 0,
    fat: 3.6,
    price: 5,
    micros: { vitaminC: 0, calcium: 0 },
  },
  {
    name: "Broccoli",
    protein: 2.8,
    carbs: 7,
    fat: 0.3,
    price: 2,
    micros: { vitaminC: 89.2, calcium: 47 },
  },
  {
    name: "Almonds",
    protein: 21,
    carbs: 22,
    fat: 50,
    price: 10,
    micros: { vitaminC: 0, calcium: 264 },
  },
  {
    name: "Oats",
    protein: 13,
    carbs: 68,
    fat: 6,
    price: 1.5,
    micros: { vitaminC: 0, calcium: 54 },
  },
  {
    name: "Salmon",
    protein: 25,
    carbs: 0,
    fat: 13,
    price: 8,
    micros: { vitaminC: 0, calcium: 9 },
  },
  {
    name: "Egg",
    protein: 13,
    carbs: 1.1,
    fat: 10,
    price: 3,
    micros: { vitaminC: 0, calcium: 56 },
  },
  {
    name: "Spinach",
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    price: 2,
    micros: { vitaminC: 28, calcium: 99 },
  },
  {
    name: "Quinoa",
    protein: 14,
    carbs: 64,
    fat: 6,
    price: 4,
    micros: { vitaminC: 0, calcium: 47 },
  },
  {
    name: "Greek Yogurt",
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    price: 4,
    micros: { vitaminC: 0, calcium: 110 },
  },
  {
    name: "Tofu",
    protein: 8,
    carbs: 2,
    fat: 4.8,
    price: 2.5,
    micros: { vitaminC: 0, calcium: 350 },
  },
  {
    name: "Avocado",
    protein: 2,
    carbs: 9,
    fat: 15,
    price: 3.5,
    micros: { vitaminC: 10, calcium: 12 },
  },
  {
    name: "Sweet Potato",
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    price: 1.8,
    micros: { vitaminC: 2.4, calcium: 30 },
  },
  {
    name: "Lentils",
    protein: 9,
    carbs: 20,
    fat: 0.4,
    price: 1.2,
    micros: { vitaminC: 0, calcium: 19 },
  },
  {
    name: "Cheddar Cheese",
    protein: 25,
    carbs: 1.3,
    fat: 33,
    price: 6,
    micros: { vitaminC: 0, calcium: 721 },
  },
];

module.exports = ingredients;
